### PR TITLE
DuplicateInList.cs : now we can find multiple duplicates and print it

### PR DESCRIPTION
**Pull request by christianbender**
* I changed the method ```FindDuplicate```. Now the method can find multiple duplicates and returns it as a list.   
* I changed the method ```InitLinkedList()``` for the new version.   
* I changed the ```Main``` for the new version.

### CODE REVIEW

**Comment by AustinTice** [comment]
Awesome work @christianbender ! You're absolutely killing it with these algorithm solutions! We will get these all reviewed and published soon! :D Keep it up!

**Comment by christianbender** [comment]
@AustinTice 
Thanks for the compliments. 
greetings from Germany

**Comment by AustinTice** [comment]
And greetings to you from America my friend!

**Comment by JGFM4** [comment]
@AustinTice The definition of the problem in the `README.md` file does not explicitly specify if the first number that has a duplicate should be returned or all the duplicates be returned in form of a list (See below).

> If the list contains any duplicates return the number, otherwise return -1.

We should clarify the problem definition. Is the algorithm to return the first duplicate that is found, or return the list of elements that have duplicates?

**Comment by AustinTice** [comment]
How does this revision sound?

> If the list contains any duplicates return the number(s) found, otherwise return -1.

Infers there could be more than 1 number found. If this still seems too broad, please inform. 

Good point though. Our challenges need to specify exactly what their solving for.

**Comment by AustinTice** [comment]
That sounds fine. Feel free to edit! @JGFM4

**Comment by JGFM4** [comment]
Will do shortly. I'll accept this PR after the modification.

**Pull request merged**
