### PR TITLE
Improved solution to FizzBuzz.

### PR DESCRIPTION
**Pull request by Fiddle-N**
My Python FizzBuzz solution is improved compared to the previous one - by using an empty string as a base, fewer if-statements and only one print call is required.

### CODE REVIEW

**Comment by JGFM4** [comment]
The 2 solutions are equivalent (See #4 for range fix).

I agree with Austin, multiple solutions for the same problem could be good to add since there are multiple ways of solving problems. @AustinTice , maybe you could add a naming convention for files in the README.md, example `X_Y.py` where X is the problem name and Y is the solution number.

**Comment by AustinTice** [comment]
@JGFM4 I will come up with something similar to that tonight. Good insight.

**Comment by JGFM4** [comment]
@AustinTice awesome. You may also want to figure out a hierarchy for the files/folders and how algorithms should be organized. It'll help to keep things tidy

**Comment by JGFM4** [comment]
Close as per Austin's previous comment. A standardized format will be available soon to deal with the "best solution" format.

**Pull request closed without merging**
